### ISSUE TITLE
PHP Warning: Illegal string offset 'rates'

### ISSUE THREAD

**Issue by Olsm** [WeProgramIT/cryptowoo-monero-addon#17]
@Wegerich reported this earlier. He said that he is getting this issue every few minutes.

`PHP Warning: Illegal string offset 'rates' in /cryptowoo-monero-addon/cryptowoo-monero-addon.php on line 953`

**Comment by Olsm** [comment]
@Wegerich which exchange are you using for Monero? Please check if the exchange rates are really updating in the database maintenance page. You can try Poloniex which is working for me. If that was the issue let me know which exchange cause it.

**Comment by Wegerich** [comment]
Poloniex, and yes, it is fully up to date.

It does seem to log every time exchange rates are updated. 

The error started occurring on [26-Dec-2019 18:32:08 UTC]. I don't think I changed anything on this day.

**Comment by Olsm** [comment]
Thank you for the bug report. The issue has been solved in commit b5714a5a707636fd2c9510c85eae0849a5a52839

It will be added to version 1.0.6 but you can download it already now from master branch or manually edit the file with the change here to stop this from spamming your logs.

**Comment by Wegerich** [comment]
Thanks, updated, that seems to have silenced the error.
