### ISSUE TITLE
Monero Wallet Address

### ISSUE THREAD

**Issue by IndeedMiners** [WeProgramIT/cryptowoo-monero-addon#2]
No input for Monero wallet address in HD wallets.

**Comment by Olsm** [comment]
I apologize for the late answer.

This addon is not yet finished.
As you can see there is no release yet.
It is a work in progress that will finish soon.

The input for Monero address will come.
New version of CryptoWoo will support it.

I will keep this open and inform when ready.

Thanks for your patience.

**Comment by Olsm** [comment]
@IndeedMiners release was July 27
https://github.com/WeProgramIT/cryptowoo-monero-addon/releases/tag/v1.0
